name: Kustomize Declarative Test

on:
  pull_request:
  push:
    branches:
      - main

env:
  KUTTL_VERSION: "v0.25.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Start Kind Cluster
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      # Install Krew
      - name: Install Krew
        run: |
          (
            set -x; cd "$(mktemp -d)" &&
            OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
            ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64/arm64/')" &&
            KREW="krew-${OS}_${ARCH}" &&
            curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
            tar zxvf "${KREW}.tar.gz" &&
            ./"${KREW}" install krew
          )
          # 关键步骤：将 krew 的 bin 目录添加到 GitHub Actions 的全局 PATH 中
          echo "${KREW_ROOT:-$HOME/.krew}/bin" >> $GITHUB_PATH

      # Install KUTTL CLI
      - name: Install KUTTL
        run: |
          kubectl krew install kuttl
          kubectl kuttl test --help

      # Run KUTTL Tests
      - name: Run KUTTL Tests
        run: |
          kubectl kuttl test
